# Generated by Django 4.1.4 on 2022-12-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRAND_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRAND_NAME', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORY_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_NAME', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LOGIN_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PHONE_NO', models.IntegerField()),
                ('PASSWORD', models.CharField(max_length=300)),
                ('DP', models.ImageField(upload_to='photos')),
                ('ROLE', models.IntegerField(choices=[(0, 'ADMIN'), (1, 'USER')])),
                ('STATUS', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')])),
                ('NAME', models.CharField(max_length=300)),
                ('DOB', models.DateTimeField()),
                ('ADDRESS', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SHOES_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIZE', models.IntegerField()),
                ('COLOR', models.CharField(max_length=300)),
                ('TYPE', models.CharField(max_length=300)),
                ('NAME', models.CharField(max_length=300)),
                ('SHOE_PHOTO', models.ImageField(upload_to='photos')),
                ('BRAND_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoe.brand_table')),
                ('CATEGORY_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoe.category_table')),
            ],
        ),
    ]
