# Generated by Django 4.1.4 on 2022-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0002_contact_table_stock_table_order_table_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes_table',
            name='PRICE',
            field=models.IntegerField(default=100),
        ),
    ]
