# Generated by Django 4.1.4 on 2022-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0003_shoes_table_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_table',
            name='FULL_NAME',
            field=models.CharField(default='', max_length=300),
        ),
    ]
