# Generated by Django 4.1.4 on 2022-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_contact_table_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_table',
            name='BRAND_ID',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='L_ID',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='SHOES_ID',
        ),
        migrations.AlterField(
            model_name='cart_table',
            name='DATE',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
