# Generated by Django 4.1.4 on 2022-12-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0007_cart_table_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='CATEGORY_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoe.category_table'),
        ),
        migrations.AddField(
            model_name='cart_table',
            name='L_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoe.login_table'),
        ),
    ]
