# Generated by Django 4.1.4 on 2022-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0008_cart_table_category_id_cart_table_l_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEW_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEWNAME', models.CharField(max_length=300)),
            ],
        ),
    ]
