# Generated by Django 4.1.4 on 2022-12-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0009_new_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEW_MODEL',
        ),
    ]
