# Generated by Django 4.1.4 on 2022-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0011_cart_table_final_price_cart_table_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='CART_TOTAL',
            field=models.IntegerField(default=50),
        ),
    ]
