# Generated by Django 4.1.4 on 2022-12-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0012_cart_table_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_table',
            name='CART_TOTAL',
        ),
    ]
