# Generated by Django 4.1.4 on 2022-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0014_rename_order_name_order_table_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='TOTAL_AMOUNT',
            field=models.IntegerField(default=0),
        ),
    ]
