# Generated by Django 4.1.4 on 2022-12-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0015_alter_order_table_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='ORDER_STATUS',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='PAYMENT_STATUS',
            field=models.CharField(default='', max_length=300),
        ),
    ]
