# Generated by Django 4.1.4 on 2022-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0016_alter_order_table_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='COMMENT',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='ADDRESS',
            field=models.CharField(max_length=500),
        ),
    ]
